// Copyright IBM Corp. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/gob"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strconv"
	"sync"
	"time"

	gogoproto "github.com/gogo/protobuf/proto"
	smart "github.com/hyperledger-labs/SmartBFT/pkg/api"
	smartbft "github.com/hyperledger-labs/SmartBFT/pkg/consensus"
	"github.com/hyperledger-labs/SmartBFT/pkg/metrics/disabled"
	bft "github.com/hyperledger-labs/SmartBFT/pkg/types"
	"github.com/hyperledger-labs/SmartBFT/pkg/wal"
	adaptivetimers "github.com/hyperledger-labs/SmartBFT/proto/adaptive_timers"
	"github.com/hyperledger-labs/SmartBFT/smartbftprotos"
	"google.golang.org/protobuf/proto"
)

// reportClientID is a constant so that two nodes submitting different report
// sets for the same episode produce the same bft.RequestInfo. That is what
// makes SmartBFT's request pool treat them as one request: the second variant
// is rejected on admission, and whichever variant is ordered evicts the others
// from every node's pool when it is delivered.
const reportClientID = "reports"

const (
	deliverQueueSize = 64
	// The report chain carries one small batch per node per episode. Its
	// timeouts are fixed on purpose: this is the control plane that carries
	// timeout recommendations, so it must never be tuned by the recommendations
	// it carries.
	reportBatchMaxCount     = 32
	reportBatchMaxInterval  = 20 * time.Millisecond
	reportRequestTimeout    = 5 * time.Second
	reportViewChangeTimeout = 20 * time.Second
	reportRequestMaxBytes   = 1024 * 1024
)

type blockData struct {
	Requests [][]byte
}

type blockHeader struct {
	PrevHash string
	DataHash string
	Sequence int64
}

func encodeBlockData(data blockData) []byte {
	var out bytes.Buffer
	if err := gob.NewEncoder(&out).Encode(data); err != nil {
		panic(fmt.Sprintf("encode report block: %v", err))
	}
	return out.Bytes()
}

func decodeBlockData(raw []byte) (blockData, error) {
	var data blockData
	err := gob.NewDecoder(bytes.NewReader(raw)).Decode(&data)
	return data, err
}

func hashBytes(raw []byte) string {
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:])
}

func reportRequestInfo(episode uint32) bft.RequestInfo {
	return bft.RequestInfo{
		ClientID: reportClientID,
		ID:       strconv.FormatUint(uint64(episode), 10),
	}
}

// The adaptive_timers stubs are generated by gogo protobuf while smartbftprotos
// uses the google runtime, so report batches must be (un)marshaled with gogo.
func decodeReportBatch(raw []byte) (*adaptivetimers.ReportBatch, error) {
	batch := &adaptivetimers.ReportBatch{}
	if err := gogoproto.Unmarshal(raw, batch); err != nil {
		return nil, fmt.Errorf("decode report batch: %w", err)
	}
	return batch, nil
}

func encodeReportBatch(batch *adaptivetimers.ReportBatch) ([]byte, error) {
	return gogoproto.Marshal(batch)
}

type reportNodeOptions struct {
	ID        uint64
	Hosts     []hostEntry
	Protocol  adaptivetimers.Protocol
	DataDir   string
	Logger    smart.Logger
	Transport *reportTransport
	Agent     *agentClient
}

// reportNode runs one replica of the report chain. Its state machine is
// deliberately trivial: an ordered stream of agreed ReportBatches, each handed
// to the local learning agent exactly once.
type reportNode struct {
	id        uint64
	protocol  adaptivetimers.Protocol
	numNodes  int
	quorum    int
	logger    smart.Logger
	transport *reportTransport
	agent     *agentClient
	consensus *smartbft.Consensus

	clock     *time.Ticker
	viewClock *time.Ticker

	lock             sync.Mutex
	prevHash         string
	lastDecision     bft.Decision
	haveDecision     bool
	highestDelivered uint32

	deliverQueue chan *adaptivetimers.ReportBatch
	stopChan     chan struct{}
	stopOnce     sync.Once
	doneWG       sync.WaitGroup
}

func newReportNode(opts reportNodeOptions) (*reportNode, error) {
	nodeDir := filepath.Join(opts.DataDir, fmt.Sprintf("sharing-node-%d", opts.ID))
	metricsProvider := &disabled.Provider{}
	walMetrics := wal.NewMetrics(metricsProvider, "sharing")
	bftMetrics := smart.NewMetrics(metricsProvider, "sharing")

	writeAheadLog, err := wal.Create(opts.Logger, nodeDir, &wal.Options{
		Metrics: walMetrics.With("node", fmt.Sprintf("%d", opts.ID)),
	})
	if err != nil {
		return nil, fmt.Errorf("create report chain WAL for node %d: %w", opts.ID, err)
	}

	n := &reportNode{
		id:           opts.ID,
		protocol:     opts.Protocol,
		numNodes:     len(opts.Hosts),
		quorum:       quorum(len(opts.Hosts)),
		logger:       opts.Logger,
		transport:    opts.Transport,
		agent:        opts.Agent,
		clock:        time.NewTicker(10 * time.Millisecond),
		viewClock:    time.NewTicker(100 * time.Millisecond),
		deliverQueue: make(chan *adaptivetimers.ReportBatch, deliverQueueSize),
		stopChan:     make(chan struct{}),
	}

	config := bft.DefaultConfig
	config.SelfID = opts.ID
	config.RequestBatchMaxCount = reportBatchMaxCount
	config.RequestBatchMaxInterval = reportBatchMaxInterval
	config.RequestPoolSize = 1024
	config.RequestMaxBytes = reportRequestMaxBytes
	config.RequestBatchMaxBytes = reportRequestMaxBytes * reportBatchMaxCount
	config.RequestForwardTimeout = reportRequestTimeout
	config.RequestComplainTimeout = reportRequestTimeout
	config.RequestAutoRemoveTimeout = 3 * reportRequestTimeout
	config.ViewChangeTimeout = reportViewChangeTimeout
	config.LeaderHeartbeatTimeout = 30 * time.Second
	config.LeaderRotation = false
	config.DecisionsPerLeader = 0

	n.consensus = &smartbft.Consensus{
		Config:             config,
		ViewChangerTicker:  n.viewClock.C,
		Scheduler:          n.clock.C,
		Logger:             opts.Logger,
		Metrics:            bftMetrics,
		Comm:               n,
		Signer:             n,
		MembershipNotifier: n,
		Verifier:           n,
		Application:        n,
		Assembler:          n,
		RequestInspector:   n,
		Synchronizer:       n,
		WAL:                writeAheadLog,
		Metadata: &smartbftprotos.ViewMetadata{
			LatestSequence: 0,
			ViewId:         0,
		},
	}

	if err := n.consensus.Start(); err != nil {
		n.clock.Stop()
		n.viewClock.Stop()
		return nil, fmt.Errorf("start report chain consensus for node %d: %w", opts.ID, err)
	}
	n.startDeliveryWorker()
	return n, nil
}

// startDeliveryWorker keeps the agent hand-off off the consensus thread. The
// agent applies aggregated rewards and runs model inference under a global
// lock, so calling it inline from Deliver would stall the report chain.
func (n *reportNode) startDeliveryWorker() {
	n.doneWG.Add(1)
	go func() {
		defer n.doneWG.Done()
		for {
			select {
			case <-n.stopChan:
				return
			case batch := <-n.deliverQueue:
				n.agent.deliverConsensus(batch)
			}
		}
	}()
}

func (n *reportNode) stop() {
	n.stopOnce.Do(func() { close(n.stopChan) })
	n.clock.Stop()
	n.viewClock.Stop()
	n.consensus.Stop()
	n.doneWG.Wait()
}

// submit hands a locally collected batch to the report chain. Duplicate
// episodes are expected: every node submits the same episode independently, and
// only one submission needs to survive.
func (n *reportNode) submit(raw []byte) error {
	return n.consensus.SubmitRequest(raw)
}

func (n *reportNode) handleConsensusMessage(from uint64, raw []byte) error {
	msg := &smartbftprotos.Message{}
	if err := proto.Unmarshal(raw, msg); err != nil {
		return fmt.Errorf("decode report consensus message: %w", err)
	}
	n.consensus.HandleMessage(from, msg)
	return nil
}

func (n *reportNode) handleForwardedRequest(from uint64, raw []byte) error {
	if _, err := n.VerifyRequest(raw); err != nil {
		return err
	}
	return n.consensus.HandleRequest(from, raw)
}

func (n *reportNode) leaderID() uint64 {
	return n.consensus.GetLeaderID()
}

// --- bft.Comm ---

func (n *reportNode) Nodes() []uint64 {
	return n.transport.nodeIDs()
}

func (n *reportNode) SendConsensus(targetID uint64, message *smartbftprotos.Message) {
	n.transport.sendConsensus(targetID, message)
}

func (n *reportNode) SendTransaction(targetID uint64, request []byte) {
	n.transport.sendTransaction(targetID, request)
}

// --- bft.RequestInspector ---

func (n *reportNode) RequestID(raw []byte) bft.RequestInfo {
	batch, err := decodeReportBatch(raw)
	if err != nil {
		return bft.RequestInfo{}
	}
	return reportRequestInfo(batch.Episode)
}

// --- bft.Verifier ---

// VerifyRequest performs structural validation only. Report signing is off in
// these experiments, so individual reports inside a batch are not authenticated
// here; the agent applies the same policy.
func (n *reportNode) VerifyRequest(raw []byte) (bft.RequestInfo, error) {
	batch, err := decodeReportBatch(raw)
	if err != nil {
		return bft.RequestInfo{}, err
	}
	if batch.Protocol != adaptivetimers.Protocol_PROTOCOL_UNSPECIFIED && batch.Protocol != n.protocol {
		return bft.RequestInfo{}, fmt.Errorf("report batch protocol mismatch: expected=%s got=%s",
			n.protocol, batch.Protocol)
	}
	if len(batch.Reports) < n.quorum {
		return bft.RequestInfo{}, fmt.Errorf("report batch for episode %d has %d reports, need at least %d",
			batch.Episode, len(batch.Reports), n.quorum)
	}
	seen := make(map[uint32]struct{}, len(batch.Reports))
	for _, report := range batch.Reports {
		if report.Episode != batch.Episode {
			return bft.RequestInfo{}, fmt.Errorf("report from node %d carries episode %d, batch is episode %d",
				report.NodeId, report.Episode, batch.Episode)
		}
		if _, duplicate := seen[report.NodeId]; duplicate {
			return bft.RequestInfo{}, fmt.Errorf("report batch for episode %d has duplicate node %d",
				batch.Episode, report.NodeId)
		}
		seen[report.NodeId] = struct{}{}
	}
	return reportRequestInfo(batch.Episode), nil
}

func (n *reportNode) VerifyProposal(proposal bft.Proposal) ([]bft.RequestInfo, error) {
	data, err := decodeBlockData(proposal.Payload)
	if err != nil {
		return nil, err
	}
	requests := make([]bft.RequestInfo, 0, len(data.Requests))
	for _, raw := range data.Requests {
		info, err := n.VerifyRequest(raw)
		if err != nil {
			return nil, err
		}
		requests = append(requests, info)
	}
	return requests, nil
}

// RequestsFromProposal must agree with VerifyProposal: the infos it returns are
// what evicts pending duplicates from the pool on the view change delivery path.
func (n *reportNode) RequestsFromProposal(proposal bft.Proposal) []bft.RequestInfo {
	data, err := decodeBlockData(proposal.Payload)
	if err != nil {
		return nil
	}
	requests := make([]bft.RequestInfo, 0, len(data.Requests))
	for _, raw := range data.Requests {
		info := n.RequestID(raw)
		if info.ClientID == "" && info.ID == "" {
			continue
		}
		requests = append(requests, info)
	}
	return requests
}

func (n *reportNode) VerifyConsenterSig(signature bft.Signature, _ bft.Proposal) ([]byte, error) {
	return signature.Msg, nil
}

func (n *reportNode) VerifySignature(_ bft.Signature) error {
	return nil
}

func (n *reportNode) VerificationSequence() uint64 {
	return 0
}

func (n *reportNode) AuxiliaryData(msg []byte) []byte {
	return msg
}

// --- bft.Signer ---

func (n *reportNode) Sign([]byte) []byte {
	return nil
}

func (n *reportNode) SignProposal(_ bft.Proposal, auxiliaryInput []byte) *bft.Signature {
	return &bft.Signature{ID: n.id, Msg: auxiliaryInput}
}

// --- bft.MembershipNotifier ---

func (n *reportNode) MembershipChange() bool {
	return false
}

// --- bft.Assembler ---

func (n *reportNode) AssembleProposal(metadata []byte, requests [][]byte) bft.Proposal {
	payload := encodeBlockData(blockData{Requests: requests})
	md := &smartbftprotos.ViewMetadata{}
	if err := proto.Unmarshal(metadata, md); err != nil {
		panic(fmt.Sprintf("unmarshal report proposal metadata: %v", err))
	}

	n.lock.Lock()
	prevHash := n.prevHash
	n.lock.Unlock()

	header, err := json.Marshal(blockHeader{
		PrevHash: prevHash,
		DataHash: hashBytes(payload),
		Sequence: int64(md.LatestSequence),
	})
	if err != nil {
		panic(fmt.Sprintf("marshal report block header: %v", err))
	}

	return bft.Proposal{
		Header:   header,
		Payload:  payload,
		Metadata: metadata,
	}
}

// --- bft.Application ---

func (n *reportNode) Deliver(proposal bft.Proposal, signatures []bft.Signature) bft.Reconfig {
	data, err := decodeBlockData(proposal.Payload)
	if err != nil {
		n.logger.Errorf("report node %d failed to decode proposal payload: %v", n.id, err)
		return bft.Reconfig{}
	}

	md := &smartbftprotos.ViewMetadata{}
	if err := proto.Unmarshal(proposal.Metadata, md); err != nil {
		n.logger.Errorf("report node %d failed to decode proposal metadata: %v", n.id, err)
	}

	for _, raw := range data.Requests {
		batch, err := decodeReportBatch(raw)
		if err != nil {
			n.logger.Errorf("report node %d failed to decode delivered batch: %v", n.id, err)
			continue
		}
		if !n.markDelivered(batch.Episode) {
			continue
		}
		fmt.Printf("%s delivered: node=%d view=%d seq=%d episode=%d reports=%d contributors=%v\n",
			logTag("sharing"), n.id, md.GetViewId(), md.GetLatestSequence(),
			batch.Episode, len(batch.Reports), contributorIDs(batch))
		n.enqueueDelivery(batch)
	}

	n.recordDecision(proposal, signatures)
	return bft.Reconfig{InLatestDecision: false}
}

func (n *reportNode) markDelivered(episode uint32) bool {
	n.lock.Lock()
	defer n.lock.Unlock()
	if episode <= n.highestDelivered {
		return false
	}
	n.highestDelivered = episode
	return true
}

func (n *reportNode) recordDecision(proposal bft.Proposal, signatures []bft.Signature) {
	n.lock.Lock()
	defer n.lock.Unlock()
	n.prevHash = proposal.Digest()
	n.lastDecision = bft.Decision{
		Proposal:   cloneProposal(proposal),
		Signatures: cloneSignatures(signatures),
	}
	n.haveDecision = true
}

func (n *reportNode) latestDecision() (bft.Decision, bool) {
	n.lock.Lock()
	defer n.lock.Unlock()
	if !n.haveDecision {
		return bft.Decision{}, false
	}
	return bft.Decision{
		Proposal:   cloneProposal(n.lastDecision.Proposal),
		Signatures: cloneSignatures(n.lastDecision.Signatures),
	}, true
}

func (n *reportNode) enqueueDelivery(batch *adaptivetimers.ReportBatch) {
	select {
	case n.deliverQueue <- batch:
	case <-n.stopChan:
	default:
		fmt.Printf("%s dropped delivery: node=%d episode=%d queue full\n",
			logTag("sharing"), n.id, batch.Episode)
	}
}

func contributorIDs(batch *adaptivetimers.ReportBatch) []uint32 {
	ids := make([]uint32, 0, len(batch.Reports))
	for _, report := range batch.Reports {
		ids = append(ids, report.NodeId)
	}
	return ids
}

func cloneProposal(proposal bft.Proposal) bft.Proposal {
	return bft.Proposal{
		Payload:              append([]byte(nil), proposal.Payload...),
		Header:               append([]byte(nil), proposal.Header...),
		Metadata:             append([]byte(nil), proposal.Metadata...),
		VerificationSequence: proposal.VerificationSequence,
	}
}

func cloneSignatures(signatures []bft.Signature) []bft.Signature {
	if len(signatures) == 0 {
		return nil
	}
	cloned := make([]bft.Signature, 0, len(signatures))
	for _, signature := range signatures {
		cloned = append(cloned, bft.Signature{
			ID:    signature.ID,
			Value: append([]byte(nil), signature.Value...),
			Msg:   append([]byte(nil), signature.Msg...),
		})
	}
	return cloned
}

func logTag(component string) string {
	return fmt.Sprintf("[%s %s]", component, time.Now().Format("2006-01-02T15:04:05.000Z07:00"))
}
